mlm_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.routers import DefaultRouter


from .views.mlm_views import *

# Create a router and register all the viewsets
router = DefaultRouter()


urlpatterns = [
    # Home page
    path("", index, name="index"),
    path("index", index, name="index"),
]

mountainlionmovies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mlm_app.urls")),

]

mlm_app/models/film_informational_models.py
from django.db import models
from django.urls import reverse


class Collection(models.Model):
    tmdb_id = models.IntegerField()
    name = models.CharField(max_length=200)
    poster_path = models.CharField(max_length=200, blank=True, null=True)
    backdrop_path = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name


class Company(models.Model):
    tmdb_id = models.IntegerField(unique=True, null=True)
    company = models.CharField(max_length=200)

    def __str__(self):
        return self.company


class Country(models.Model):
    code = models.CharField(max_length=10)
    country = models.CharField(max_length=200)

    def __str__(self):
        return self.country


class Film(models.Model):
    adult = models.BooleanField(null=True, blank=True)
    backdrop_path = models.CharField(max_length=200, blank=True, null=True)
    belongs_to_collection = models.BooleanField(default=False)
    budget = models.IntegerField(null=True)
    homepage = models.CharField(max_length=200, blank=True, null=True)
    imdb_id = models.CharField(max_length=20, blank=True, null=True)
    original_title = models.CharField(max_length=200)
    overview = models.CharField(max_length=2000, blank=True, null=True)
    popularity = models.DecimalField(decimal_places=6, max_digits=20)
    poster_path = models.CharField(max_length=200, blank=True, null=True)
    release_date = models.DateField(null=True, blank=True)
    revenue = models.BigIntegerField(null=True)
    runtime = models.IntegerField(null=True)
    status = models.CharField(max_length=200, blank=True, null=True)
    tagline = models.CharField(max_length=500, blank=True, null=True)
    title = models.CharField(max_length=200)
    tmdb_id = models.IntegerField(unique=True, null=True)
    vote_average = models.DecimalField(
        decimal_places=3, max_digits=6, null=True, blank=True
    )
    vote_count = models.IntegerField(null=True)
    mlm_rating = models.DecimalField(
        decimal_places=6, max_digits=20, null=True
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("film-detail", args=[str(self.id)])


class Genre(models.Model):
    tmdb_id = models.IntegerField(unique=True, null=True)
    genre = models.CharField(unique=True, max_length=200)

    def __str__(self):
        return self.genre


class Keyword(models.Model):
    tmdb_id = models.IntegerField(unique=True, null=True)
    keyword = models.CharField(unique=True, max_length=200)

    def __str__(self):
        return self.keyword


class Language(models.Model):
    code = models.CharField(null=True, unique=True, max_length=4)
    language = models.CharField(null=True, max_length=200)

    def __str__(self):
        return self.language


class Person(models.Model):
    adult = models.BooleanField(null=True, blank=True)
    gender = models.IntegerField(null=True, blank=True)
    tmdb_id = models.IntegerField(unique=True)
    known_for_department = models.CharField(
        max_length=200, null=True, blank=True
    )
    name = models.CharField(max_length=200, null=True, blank=True)
    popularity = models.DecimalField(
        decimal_places=3, null=True, blank=True, max_digits=10
    )
    profile_path = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("person-detail", args=[str(self.id)])

mlm_app/models/linking_tables.py
from datetime import date
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError


class LT_Films_Cast(models.Model):
    film = models.ForeignKey(
        "mlm_app.Film", on_delete=models.DO_NOTHING, null=True
    )
    person = models.ForeignKey(
        "mlm_app.Person", on_delete=models.DO_NOTHING, null=True
    )
    cast_id = models.IntegerField()
    character = models.CharField(null=True, max_length=200)
    credit_id = models.CharField(max_length=200, null=True)
    order = models.IntegerField(null=True)


class LT_Films_Companies(models.Model):
    film = models.ForeignKey("mlm_app.Film", on_delete=models.DO_NOTHING)
    company = models.ForeignKey(
        "mlm_app.Company", on_delete=models.DO_NOTHING
    )


class LT_Films_Countries(models.Model):
    film = models.ForeignKey("mlm_app.Film", on_delete=models.DO_NOTHING)
    country = models.ForeignKey(
        "mlm_app.Country", on_delete=models.DO_NOTHING
    )


class LT_Films_Crew(models.Model):
    film = models.ForeignKey(
        "mlm_app.Film", on_delete=models.DO_NOTHING, null=True
    )
    person = models.ForeignKey(
        "mlm_app.Person", on_delete=models.DO_NOTHING, null=True
    )
    credit_id = models.CharField(max_length=200, null=True)
    department = models.CharField(max_length=200, null=True)
    job = models.CharField(max_length=200, null=True)


class LT_Films_Genres(models.Model):
    film = models.ForeignKey("mlm_app.Film", on_delete=models.DO_NOTHING)
    genre = models.ForeignKey("mlm_app.Genre", on_delete=models.DO_NOTHING)

    class Meta:
        unique_together = ("film", "genre")


class LT_Films_Keywords(models.Model):
    film = models.ForeignKey("mlm_app.Film", on_delete=models.DO_NOTHING)
    keyword = models.ForeignKey(
        "mlm_app.Keyword", on_delete=models.DO_NOTHING
    )

    def get_absolute_url(self):
        return reverse("LT_Films_Keywords-detail", args=[str(self.id)])

    class Meta:
        unique_together = ("film", "keyword")


class LT_Films_Languages(models.Model):
    film = models.ForeignKey("mlm_app.Film", on_delete=models.DO_NOTHING)
    language = models.ForeignKey(
        "mlm_app.Language", on_delete=models.DO_NOTHING
    )


class LT_Viewer_Cosine_Similarity(models.Model):
    viewer_1 = models.ForeignKey(
        "mlm_app.Viewer", on_delete=models.PROTECT, related_name="viewer_1"
    )
    viewer_2 = models.ForeignKey(
        "mlm_app.Viewer", on_delete=models.PROTECT, related_name="viewer_2"
    )
    cosine_similarity = models.DecimalField(
        decimal_places=4, max_digits=5, null=True
    )

    class Meta:
        unique_together = ("viewer_1", "viewer_2")
        indexes = [
            models.Index(fields=["viewer_1", "viewer_2"]),
        ]

    def clean(self):
        if self.viewer_1 == self.viewer_2:
            raise ValidationError(
                "A viewer cannot have a cosine similarity score with themselves."
            )

    def save(self, *args, **kwargs):
        if self.viewer_1.id > self.viewer_2.id:
            self.viewer_1, self.viewer_2 = self.viewer_2, self.viewer_1
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Cosine Similarity between {self.viewer_1} and {self.viewer_2}: {self.cosine_similarity}"


class LT_Viewer_Ratings(models.Model):
    viewer = models.ForeignKey(
        "mlm_app.Viewer", on_delete=models.DO_NOTHING, null=True
    )
    film_a = models.ForeignKey(
        "mlm_app.Film",
        on_delete=models.DO_NOTHING,
        related_name="film_a",
        null=True,
    )
    film_b = models.ForeignKey(
        "mlm_app.Film",
        on_delete=models.DO_NOTHING,
        related_name="film_b",
        null=True,
    )
    date = models.DateField(default=date.today, null=True)
    a_points = models.DecimalField(
        decimal_places=1, max_digits=3, default=0, null=True
    )
    b_points = models.DecimalField(
        decimal_places=1, max_digits=3, default=0, null=True
    )

    class Meta:
        unique_together = ("viewer", "film_a", "film_b")


class LT_Viewer_Seen(models.Model):
    viewer = models.ForeignKey(
        "mlm_app.Viewer", on_delete=models.DO_NOTHING, null=True
    )
    film = models.ForeignKey(
        "mlm_app.Film", on_delete=models.DO_NOTHING, null=True
    )
    seen_film = models.BooleanField(default=False, null=True)
    viewer_rating = models.DecimalField(
        decimal_places=8, max_digits=9, default=0.5, null=True
    )

    class Meta:
        unique_together = ("viewer", "film")


class LT_Viewer_Watchlist(models.Model):
    viewer = models.ForeignKey(
        "mlm_app.Viewer", on_delete=models.DO_NOTHING
    )
    film = models.ForeignKey("mlm_app.Film", on_delete=models.DO_NOTHING)
    watchlist = models.BooleanField(default=False)

    class Meta:
        indexes = [
            models.Index(fields=["viewer", "film"]),
        ]

mlm_app/models/social_models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Viewer(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    profile_picture = models.ImageField(
        upload_to="profile_pictures/",
        blank=True,
        null=True,
        default="profile_pictures/default_pfp.jpg",
    )
    friends = models.ManyToManyField("self", blank=True)

    def has_seen_film(self, film):
        # Use string reference for LT_Viewer_Seen
        return self._meta.model._default_manager.filter(
            viewer=self, film=film, seen_film=True
        ).exists()

    def is_in_watchlist(self, film):
        # Use string reference for LT_Viewer_Watchlist
        return self._meta.model._default_manager.filter(
            viewer=self, film=film, watchlist=True
        ).exists()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("profile_viewer", args=[str(self.id)])

    def add_friend(self, viewer):
        if not self.is_friends_with(viewer):
            self.friends.add(viewer)
            self.save()

    def remove_friend(self, viewer):
        if self.is_friends_with(viewer):
            self.friends.remove(viewer)
            self.save()

    def is_friends_with(self, viewer):
        return self.friends.filter(id=viewer.id).exists()


class FriendRequest(models.Model):
    sender = models.ForeignKey(
        "Viewer", related_name="sent_requests", on_delete=models.CASCADE
    )
    receiver = models.ForeignKey(
        "Viewer", related_name="received_requests", on_delete=models.CASCADE
    )
    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("accepted", "Accepted"),
        ("rejected", "Rejected"),
    ]
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="pending"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    accepted_at = models.DateTimeField(null=True)
    rejected_at = models.DateTimeField(null=True)

    def accept(self):
        self.status = "accepted"
        self.sender.add_friend(self.receiver)
        self.receiver.add_friend(self.sender)
        self.save()

    def reject(self):
        self.status = "rejected"
        self.save()

    def __str__(self):
        return f"{self.sender.name} -> {self.receiver.name} ({self.status})"


class FeedEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(
        "mlm_app.Film", on_delete=models.CASCADE
    )  # Reference Film by string
    # e.g., "added to watchlist" or "marked as seen"
    action = models.CharField(max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True)


class Like(models.Model):
    feed_entry = models.ForeignKey(
        "FeedEntry", related_name="likes", on_delete=models.CASCADE
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(models.Model):
    feed_entry = models.ForeignKey(
        "FeedEntry", related_name="comments", on_delete=models.CASCADE
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


class Notification(models.Model):
    TYPE_CHOICES = [
        ("like", "Like"),
        ("comment", "Comment"),
    ]

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notifications"
    )
    feed_entry = models.ForeignKey("FeedEntry", on_delete=models.CASCADE)
    notification_type = models.CharField(max_length=10, choices=TYPE_CHOICES)
    is_read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.notification_type} on {self.feed_entry}"

mlm_app/views.py
from django.shortcuts import render

# Create your views here.

mlm_app/views/mlm_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import ListView
from ..models import Film, LT_Viewer_Seen, LT_Viewer_Watchlist, Viewer





def index(request):
    return render(request, "mlm_app/index.html")

mlm_app/templates/mlm_app/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Mountain Lion Movies</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles1.css' %}" />
    <link rel="icon" href="{% static 'images/favicon.ico' %}" />
    <!-- Additional Scripts -->
    <script src="{% static 'static.js' %}"></script>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light w-100 justify-content-center">
      <div class="container-fluid d-flex justify-content-center">
        <!-- Left: Dropdown Menu Button with Image -->
        <div style="color: black;" class="dropdown me-2">
          <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false" style="border: none; background: none;"><img src="{% static 'images/menu.png' %}" alt="Menu" height="50" /></button>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% comment %} <li><a class="dropdown-item" href="{% url 'film_list' %}">Films</a></li>
            <li><a class="dropdown-item" href="{% url 'viewers' %}">Viewers</a></li>
            <li><a class="dropdown-item" href="{% url 'search_movies' %}">Browse</a></li>
            <li><a class="dropdown-item" href="{% url 'compare_movies' %}">Rate Movies</a></li>
            {% if user.is_authenticated %}
              <li class="dropdown-item"><a class="nav-link" href="{% url 'profile' %}">Profile</a></li>
              <li class="dropdown-item">
                <form method="post" action="{% url 'logout' %}">
                  {% csrf_token %}
                  <button class="nav-link" type="submit">Logout</button>
                </form>
              </li>
            {% else %}
              <li class="dropdown-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
              <li class="dropdown-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
            {% endif %}
          </ul> {% endcomment %}
        </div>

        <!-- Center: Website Title -->
        <div class="text-center">
          <a class="navbar-brand" href="{% url 'index' %}">
            {% comment %} <img height="90" src="{% static 'images/newMountionLionLogo.png' %}" alt="Mountain Lion Logo" /> {% endcomment %}
          </a>
        </div>

        <!-- Right: Login/Profile Button, Notification Icon, and Dark Mode Toggle Switch -->
        <div class="d-flex align-items-center ms-auto">
          <!-- Search Function -->
          <div class="d-flex align-items-center">
            {% comment %} <form method="GET" action="{% url 'search_results' %}" class="d-flex" role="search"> {% endcomment %}
              <div class="input-group">
                <select name="filter" class="form-select-sm search-filter bg-secondary-subtle">
                  <option value="all">All</option>
                  <option value="viewer">Viewer</option>
                  <option value="movie">Movie</option>
                </select>
                <input type="search" class="form-control" name="q" placeholder="Search..." aria-label="Search" required>
                <button type="submit" class="btn btn-outline-warning me-2">Search</button>
              </div>
            </form>
          </div>

          <!-- Profile icon -->
          <div style="color: black;" class="dropdown me-2">
            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{% static 'images/usericon1.png' %}" alt="Menu" height="50"/>
            </button>
            {% comment %} <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'feed_page' %}">Feed</a></li>
                    <li>
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-warning dropdown-item" type="submit">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul> {% endcomment %}
          </div>

          <div class="d-flex align-items-center">
            <!-- Notification Bell with Dropdown -->
            <div class="dropdown me-3 position-relative">
              <button class="btn dropdown-toggle" type="button" id="notificationDropdown" data-bs-toggle="dropdown" aria-expanded="false" style="border: none; background: none;">
                <img src="{% static 'images/bell.png' %}" alt="Notifications" height="50" />
                <span id="notificationCount" class="notification-bubble"></span> <!-- Unread notification count -->
              </button>
              {% comment %} <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="notificationDropdown" id="notificationContainer">
                <li>
                  <a class="dropdown-item" href="{% url 'viewers' %}">
                    Friend Requests
                    {% if num_pending_requests > 0 %}
                      <span class="badge bg-danger">{{ num_pending_requests }}</span>
                    {% endif %}
                  </a>
                </li>
                <li><hr class="dropdown-divider"></li>
                <!-- Placeholder for notifications -->
                <li id="notificationsPlaceholder">
                  <div class="dropdown-item text-center text-muted">Notifications</div>
                </li>
              </ul> {% endcomment %}
            </div>
          
        

            <!-- Dark Mode Toggle Switch -->
            <div class="form-check form-switch">
              <input class="form-check-input" type="checkbox" id="darkModeSwitch" />
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      {% block content %}

      {% endblock %}
    </div>

    <!-- Bootstrap JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <!--Notification Center Script-->
    {% comment %} <script src="{% static 'scripts/notifications.js' %}"></script> {% endcomment %}
  </body>
</html>

mlm_app/templates/mlm_app/index.html
{% extends 'mlm_app/base_template.html' %}
{% load static %}
{% block content %}

  <div class="text-center">
      <img style="width: 20%; margin-top: 30px;" src="{% static 'images/mountain_lion.png' %}" class="img-fluid">
  </div>
  {% comment %} <h1>Mountain Lion Movies</h1> {% endcomment %}
  <h2 style="text-align: center; margin-top: 30px;" >Find movies and shows based on any story you love!</h2>
  <div class="page-margin">
    <h3 style="text-align: center; margin-top: 30px;">At Mountain Lion Movies, we understand the challenge of finding the perfect 
          movie to match your mood or personal tastes. Our platform is designed with simplicity 
          and ease in mind, helping you discover movies that align with your unique preferences.</h3>
      
      <div style="margin-top: 50px;" class="row justify-content-center">
        <div class="col-md-6">
          <h3 style="color: #ffb700; margin-top: 40px;">Powered by a <strong>cutting-edge recommendation engine</strong>, Mountain Lion Movies takes into account 
          a variety of factors, including:</h3>
        </div>
        <div class="col-md-6">
            <ul class="list-unstyled fade-in-list">
                <li><div style="background-color: #cfb87c;" class="custom-container"><strong>Movie Genres</strong> you love</div></li>
                <li><div style="background-color: #e3bf65;" class="custom-container"><strong>Favorite Actors</strong> and directors</div></li>
                <li><div style="background-color: #f3bc2f;" class="custom-container"><strong>User Ratings</strong> from the community</div></li>
                <li><div style="background-color: #ffb700;" class="custom-container"><strong>Your Viewing History</strong> for personalized picks</div></li>
            </ul>
        </div>

      </div>


  <h2 style="margin-top: 50px;">Popular Movies</h2>
  <p>display carosel of popular movies</p>

  <h2>Discover</h2>
  <p>display carosel of popular movies</p>

  <h2>New</h2>
  <p>display carosel of popular movies</p>

  {% comment %} IF LOGGED IN... {% endcomment %}
  <h2>Movies For You!</h2>
  <p>display carosel of user movies recommendations</p>



  </div> <!-- end page-margin divider -->

  <script>
document.addEventListener('DOMContentLoaded', function () {
    const listItems = document.querySelectorAll('.fade-in-list li');
    
    listItems.forEach((li, index) => {
        setTimeout(() => {
            li.classList.add('fade-in');
        }, index * 500); // 0.5 seconds delay for each item
    });
});

  </script>


{% endblock %}